# Generated by Django 2.2 on 2021-06-08 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='nome_da_empresa',
            new_name='nome_empresa',
        ),
    ]
